spring:
  # 配置数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:dezhi}?currentSchema=${POSTGRESQL_SCHEMA:dezhi}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}

  # 配置 redis
  data:
    redis:
      database: ${REDIS_DATABASE:0}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  # 配置 spring ai
  ai:
    # 配置 openai
    openai:
      base-url: ${OPENAI_BASE_URL}
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL}

    vectorstore:
      # 配置 weaviate
      weaviate:
        host: ${WEAVIATE_HOST}:${WEAVIATE_PORT}
        scheme: http
        headers:
          Authorization: Bearer ${WEAVIATE_API_KEY}
        object-class: ArticleChunk
        consistency-level: quorum
        filter-field:
          articleId: TEXT
          categoryId: TEXT
          status: TEXT
          title: TEXT
          uri: TEXT

dezhi:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    export-url: ${MINIO_EXPORT_URL}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket-name: ${MINIO_BUCKET_NAME:dezhi}